//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualityEditor.EditorRes {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DualityEditor.EditorRes.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string Category_Advanced {
            get {
                return ResourceManager.GetString("Category_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string Category_General {
            get {
                return ResourceManager.GetString("Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics ähnelt.
        /// </summary>
        public static string Category_Graphics {
            get {
                return ResourceManager.GetString("Category_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physics ähnelt.
        /// </summary>
        public static string Category_Physics {
            get {
                return ResourceManager.GetString("Category_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound ähnelt.
        /// </summary>
        public static string Category_Sound {
            get {
                return ResourceManager.GetString("Category_Sound", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap CursorArrow {
            get {
                object obj = ResourceManager.GetObject("CursorArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowAction {
            get {
                object obj = ResourceManager.GetObject("CursorArrowAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionMove {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionRotate {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionScale {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No information available. ähnelt.
        /// </summary>
        public static string HelpInfo_NotAvailable_Desc {
            get {
                return ResourceManager.GetString("HelpInfo_NotAvailable_Desc", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon IconCog {
            get {
                object obj = ResourceManager.GetObject("IconCog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon IconWorkingFolder {
            get {
                object obj = ResourceManager.GetObject("IconWorkingFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImageAppCreate {
            get {
                object obj = ResourceManager.GetObject("ImageAppCreate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImageTemplateCurrent {
            get {
                object obj = ResourceManager.GetObject("ImageTemplateCurrent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ImageTemplateEmpty {
            get {
                object obj = ResourceManager.GetObject("ImageTemplateEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string MenuItemName_About {
            get {
                return ResourceManager.GetString("MenuItemName_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Project... ähnelt.
        /// </summary>
        public static string MenuItemName_NewProject {
            get {
                return ResourceManager.GetString("MenuItemName_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MenuName_File {
            get {
                return ResourceManager.GetString("MenuName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string MenuName_Help {
            get {
                return ResourceManager.GetString("MenuName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MenuName_Settings {
            get {
                return ResourceManager.GetString("MenuName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        public static string MenuName_Tools {
            get {
                return ResourceManager.GetString("MenuName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string MenuName_View {
            get {
                return ResourceManager.GetString("MenuName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t import file ähnelt.
        /// </summary>
        public static string Msg_CantImport_Caption {
            get {
                return ResourceManager.GetString("Msg_CantImport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t import file &apos;{0}&apos;. The files format is not supported. ähnelt.
        /// </summary>
        public static string Msg_CantImport_Text {
            get {
                return ResourceManager.GetString("Msg_CantImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break Prefab Link? ähnelt.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action will break the objects Prefab Link. Proceed? ähnelt.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really quit? ähnelt.
        /// </summary>
        public static string Msg_ConfirmQuit_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to quit? ähnelt.
        /// </summary>
        public static string Msg_ConfirmQuit_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuit_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really quit? ähnelt.
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following Resources have been modified without saving:{0}Do you want to save them before exiting? ähnelt.
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [ and {0} more ] ähnelt.
        /// </summary>
        public static string Msg_ConfirmQuitUnsaved_Desc_More {
            get {
                return ResourceManager.GetString("Msg_ConfirmQuitUnsaved_Desc_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload Resource? ähnelt.
        /// </summary>
        public static string Msg_ConfirmReloadResource_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmReloadResource_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The currently active Resource &apos;{0}&apos; has been modified externally. Do you want to reload it from file? Any unsaved changes might be lost. ähnelt.
        /// </summary>
        public static string Msg_ConfirmReloadResource_Text {
            get {
                return ResourceManager.GetString("Msg_ConfirmReloadResource_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save current Scene? ähnelt.
        /// </summary>
        public static string Msg_EnterSandboxUnsavedScene_Caption {
            get {
                return ResourceManager.GetString("Msg_EnterSandboxUnsavedScene_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to enter Sandbox mode although the current Scene is temporary, so it won&apos;t be restored when leaving Sandbox mode. Do you want to make it restorable by saving it before? ähnelt.
        /// </summary>
        public static string Msg_EnterSandboxUnsavedScene_Desc {
            get {
                return ResourceManager.GetString("Msg_EnterSandboxUnsavedScene_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to perform task ähnelt.
        /// </summary>
        public static string Msg_ErrorPerformBigTask_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorPerformBigTask_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured while performing task &apos;{0}&apos;: {1}{2} ähnelt.
        /// </summary>
        public static string Msg_ErrorPerformBigTask_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorPerformBigTask_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t reload core plugin ähnelt.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured reloading Duality core plugins: {0}{1} ähnelt.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite file? ähnelt.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Caption {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing file &apos;{0}&apos; would overwrite an already imported file. Do you want to continue? ähnelt.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Text {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install new Template? ähnelt.
        /// </summary>
        public static string Msg_InstallNewTemplate_Caption {
            get {
                return ResourceManager.GetString("Msg_InstallNewTemplate_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Template you selected is not located inside your global Template directory. Do you wish to send it there for future usage? ähnelt.
        /// </summary>
        public static string Msg_InstallNewTemplate_Desc {
            get {
                return ResourceManager.GetString("Msg_InstallNewTemplate_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project Templates (*.zip)|*.zip ähnelt.
        /// </summary>
        public static string OpenTemplateDialog_Filters {
            get {
                return ResourceManager.GetString("OpenTemplateDialog_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Project Template.. ähnelt.
        /// </summary>
        public static string OpenTemplateDialog_Title {
            get {
                return ResourceManager.GetString("OpenTemplateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} objects ähnelt.
        /// </summary>
        public static string PropertyGrid_N_Objects {
            get {
                return ResourceManager.GetString("PropertyGrid_N_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the folder in which a new project will be created below. ähnelt.
        /// </summary>
        public static string SelectNewProjectFolderDialog_Desc {
            get {
                return ResourceManager.GetString("SelectNewProjectFolderDialog_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reloading core plugins... ähnelt.
        /// </summary>
        public static string TaskBarOverlay_ReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("TaskBarOverlay_ReloadCorePlugin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changing project data format... ähnelt.
        /// </summary>
        public static string TaskChangeDataFormat_Caption {
            get {
                return ResourceManager.GetString("TaskChangeDataFormat_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project data format has been changed to {0}. Existing Resource files will be converted shortly. ähnelt.
        /// </summary>
        public static string TaskChangeDataFormat_Desc {
            get {
                return ResourceManager.GetString("TaskChangeDataFormat_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Relocating ContentRefs... ähnelt.
        /// </summary>
        public static string TaskRenameContentRefs_Caption {
            get {
                return ResourceManager.GetString("TaskRenameContentRefs_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more Resources have been moved or renamed. Duality is searching for references to these Resources in order to update them. ähnelt.
        /// </summary>
        public static string TaskRenameContentRefs_Desc {
            get {
                return ResourceManager.GetString("TaskRenameContentRefs_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new project by cloning the current one. ähnelt.
        /// </summary>
        public static string Template_Current_Desc {
            get {
                return ResourceManager.GetString("Template_Current_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Project ähnelt.
        /// </summary>
        public static string Template_Current_Name {
            get {
                return ResourceManager.GetString("Template_Current_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project without any content. ähnelt.
        /// </summary>
        public static string Template_Empty_Desc {
            get {
                return ResourceManager.GetString("Template_Empty_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empty Project ähnelt.
        /// </summary>
        public static string Template_Empty_Name {
            get {
                return ResourceManager.GetString("Template_Empty_Name", resourceCulture);
            }
        }
    }
}
