//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.235
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualityEditor.EditorRes {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DualityEditor.EditorRes.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap CursorArrow {
            get {
                object obj = ResourceManager.GetObject("CursorArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowAction {
            get {
                object obj = ResourceManager.GetObject("CursorArrowAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionMove {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionRotate {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionRotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap CursorArrowActionScale {
            get {
                object obj = ResourceManager.GetObject("CursorArrowActionScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon Icon_Cog {
            get {
                object obj = ResourceManager.GetObject("Icon_Cog", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Icon_WorkingFolder {
            get {
                object obj = ResourceManager.GetObject("Icon_WorkingFolder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MenuName_File {
            get {
                return ResourceManager.GetString("MenuName_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string MenuName_Settings {
            get {
                return ResourceManager.GetString("MenuName_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        public static string MenuName_Tools {
            get {
                return ResourceManager.GetString("MenuName_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View ähnelt.
        /// </summary>
        public static string MenuName_View {
            get {
                return ResourceManager.GetString("MenuName_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t import file ähnelt.
        /// </summary>
        public static string Msg_CantImport_Caption {
            get {
                return ResourceManager.GetString("Msg_CantImport_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t import file &apos;{0}&apos;. The files format is not supported. ähnelt.
        /// </summary>
        public static string Msg_CantImport_Text {
            get {
                return ResourceManager.GetString("Msg_CantImport_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Break Prefab Link? ähnelt.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Caption {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action will break the objects Prefab Link. Proceed? ähnelt.
        /// </summary>
        public static string Msg_ConfirmBreakPrefabLink_Desc {
            get {
                return ResourceManager.GetString("Msg_ConfirmBreakPrefabLink_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t reload core plugin ähnelt.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Caption {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured reloading Duality core plugins: {0}{1} ähnelt.
        /// </summary>
        public static string Msg_ErrorReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("Msg_ErrorReloadCorePlugin_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite file? ähnelt.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Caption {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing file &apos;{0}&apos; would overwrite an already imported file. Do you want to continue? ähnelt.
        /// </summary>
        public static string Msg_ImportConfirmOverwrite_Text {
            get {
                return ResourceManager.GetString("Msg_ImportConfirmOverwrite_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} objects ähnelt.
        /// </summary>
        public static string PropertyGrid_N_Objects {
            get {
                return ResourceManager.GetString("PropertyGrid_N_Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reloading core plugins... ähnelt.
        /// </summary>
        public static string TaskBarOverlay_ReloadCorePlugin_Desc {
            get {
                return ResourceManager.GetString("TaskBarOverlay_ReloadCorePlugin_Desc", resourceCulture);
            }
        }
    }
}
