//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditorBase.PluginRes {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorBaseRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorBaseRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditorBase.PluginRes.EditorBaseRes", typeof(EditorBaseRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Material ähnelt.
        /// </summary>
        public static string ActionName_CreateMaterial {
            get {
                return ResourceManager.GetString("ActionName_CreateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Sound ähnelt.
        /// </summary>
        public static string ActionName_CreateSound {
            get {
                return ResourceManager.GetString("ActionName_CreateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Texture ähnelt.
        /// </summary>
        public static string ActionName_CreateTexture {
            get {
                return ResourceManager.GetString("ActionName_CreateTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angle: {0:F}° ähnelt.
        /// </summary>
        public static string CamView_Status_Angle {
            get {
                return ResourceManager.GetString("CamView_Status_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X: {0:F} ähnelt.
        /// </summary>
        public static string CamView_Status_PosX {
            get {
                return ResourceManager.GetString("CamView_Status_PosX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y: {0:F} ähnelt.
        /// </summary>
        public static string CamView_Status_PosY {
            get {
                return ResourceManager.GetString("CamView_Status_PosY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z: {0:F} ähnelt.
        /// </summary>
        public static string CamView_Status_PosZ {
            get {
                return ResourceManager.GetString("CamView_Status_PosZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string Category_Advanced {
            get {
                return ResourceManager.GetString("Category_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string Category_General {
            get {
                return ResourceManager.GetString("Category_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics ähnelt.
        /// </summary>
        public static string Category_Graphics {
            get {
                return ResourceManager.GetString("Category_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Physics ähnelt.
        /// </summary>
        public static string Category_Physics {
            get {
                return ResourceManager.GetString("Category_Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound ähnelt.
        /// </summary>
        public static string Category_Sound {
            get {
                return ResourceManager.GetString("Category_Sound", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap IconCmpCamera {
            get {
                object obj = ResourceManager.GetObject("IconCmpCamera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpCapsuleCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpCapsuleCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpCircleCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpCircleCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpRectCollider {
            get {
                object obj = ResourceManager.GetObject("IconCmpRectCollider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpSoundListener {
            get {
                object obj = ResourceManager.GetObject("IconCmpSoundListener", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpSpriteRenderer {
            get {
                object obj = ResourceManager.GetObject("IconCmpSpriteRenderer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpTransform {
            get {
                object obj = ResourceManager.GetObject("IconCmpTransform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconCmpUnknown {
            get {
                object obj = ResourceManager.GetObject("IconCmpUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon IconEye {
            get {
                object obj = ResourceManager.GetObject("IconEye", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconGameObj {
            get {
                object obj = ResourceManager.GetObject("IconGameObj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconGameObjLink {
            get {
                object obj = ResourceManager.GetObject("IconGameObjLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconGameObjLinkBroken {
            get {
                object obj = ResourceManager.GetObject("IconGameObjLinkBroken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon IconLogView {
            get {
                object obj = ResourceManager.GetObject("IconLogView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon IconObjView {
            get {
                object obj = ResourceManager.GetObject("IconObjView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon IconProjectView {
            get {
                object obj = ResourceManager.GetObject("IconProjectView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResAudioData {
            get {
                object obj = ResourceManager.GetObject("IconResAudioData", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResDrawTechnique {
            get {
                object obj = ResourceManager.GetObject("IconResDrawTechnique", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResFont {
            get {
                object obj = ResourceManager.GetObject("IconResFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResFragmentShader {
            get {
                object obj = ResourceManager.GetObject("IconResFragmentShader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResMaterial {
            get {
                object obj = ResourceManager.GetObject("IconResMaterial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResPixmap {
            get {
                object obj = ResourceManager.GetObject("IconResPixmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResPrefabEmpty {
            get {
                object obj = ResourceManager.GetObject("IconResPrefabEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResPrefabFull {
            get {
                object obj = ResourceManager.GetObject("IconResPrefabFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResRenderTarget {
            get {
                object obj = ResourceManager.GetObject("IconResRenderTarget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResScene {
            get {
                object obj = ResourceManager.GetObject("IconResScene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResShaderProgram {
            get {
                object obj = ResourceManager.GetObject("IconResShaderProgram", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResSound {
            get {
                object obj = ResourceManager.GetObject("IconResSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResTexture {
            get {
                object obj = ResourceManager.GetObject("IconResTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResUnknown {
            get {
                object obj = ResourceManager.GetObject("IconResUnknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IconResVertexShader {
            get {
                object obj = ResourceManager.GetObject("IconResVertexShader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon IconSceneView {
            get {
                object obj = ResourceManager.GetObject("IconSceneView", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application Data ähnelt.
        /// </summary>
        public static string MenuItemName_AppData {
            get {
                return ResourceManager.GetString("MenuItemName_AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Camera ähnelt.
        /// </summary>
        public static string MenuItemName_CamView {
            get {
                return ResourceManager.GetString("MenuItemName_CamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log View ähnelt.
        /// </summary>
        public static string MenuItemName_LogView {
            get {
                return ResourceManager.GetString("MenuItemName_LogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object Inspector ähnelt.
        /// </summary>
        public static string MenuItemName_ObjView {
            get {
                return ResourceManager.GetString("MenuItemName_ObjView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project View ähnelt.
        /// </summary>
        public static string MenuItemName_ProjectView {
            get {
                return ResourceManager.GetString("MenuItemName_ProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resource Inspector ähnelt.
        /// </summary>
        public static string MenuItemName_ResView {
            get {
                return ResourceManager.GetString("MenuItemName_ResView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scene View ähnelt.
        /// </summary>
        public static string MenuItemName_SceneView {
            get {
                return ResourceManager.GetString("MenuItemName_SceneView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default User Data ähnelt.
        /// </summary>
        public static string MenuItemName_UserData {
            get {
                return ResourceManager.GetString("MenuItemName_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Folder ähnelt.
        /// </summary>
        public static string NewFolderName {
            get {
                return ResourceManager.GetString("NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t move file ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantMove_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantMove_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t move file to &apos;{0}&apos; because it would overwrite an existing file. ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantMove_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantMove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t rename file ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantRename_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantRename_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t rename file to &apos;{0}&apos; because it would overwrite an existing file. ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_CantRename_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_CantRename_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected files? ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Caption {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected files? ähnelt.
        /// </summary>
        public static string ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Text {
            get {
                return ResourceManager.GetString("ProjectFolderView_MsgBox_ConfirmDeleteSelectedFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project ähnelt.
        /// </summary>
        public static string ProjectNameLabel {
            get {
                return ResourceManager.GetString("ProjectNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scene ähnelt.
        /// </summary>
        public static string SceneNameLabel {
            get {
                return ResourceManager.GetString("SceneNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unsaved Scene ähnelt.
        /// </summary>
        public static string SceneNameNotYetSaved {
            get {
                return ResourceManager.GetString("SceneNameNotYetSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected objects? ähnelt.
        /// </summary>
        public static string SceneView_MsgBox_ConfirmDeleteSelectedObjects_Caption {
            get {
                return ResourceManager.GetString("SceneView_MsgBox_ConfirmDeleteSelectedObjects_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected objects? ähnelt.
        /// </summary>
        public static string SceneView_MsgBox_ConfirmDeleteSelectedObjects_Text {
            get {
                return ResourceManager.GetString("SceneView_MsgBox_ConfirmDeleteSelectedObjects_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Linked to: {0} ähnelt.
        /// </summary>
        public static string SceneView_PrefabLink {
            get {
                return ResourceManager.GetString("SceneView_PrefabLink", resourceCulture);
            }
        }
    }
}
